artifacts_root: artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion 
  source_url: https://www.kaggle.com/datasets/uviiiii/real-estate
  local_path: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model 
  base_model_path: artifacts/prepare_base_model/base_model.keras
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.keras


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.keras


evaluation:
  track_url: https://dagshub.com/youssefBedeer/End-to-End-PlantVillage.mlflow